"""remoção de atributo desnecessario and instead of nome its name

Revision ID: 697eedd50f81
Revises: 42f7433a9b30
Create Date: 2025-04-18 22:07:07.191247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697eedd50f81'
down_revision: Union[str, None] = '42f7433a9b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lojas', sa.Column('name', sa.String(), nullable=False))
    op.add_column('lojas', sa.Column('contact', sa.String(), nullable=True))
    op.drop_constraint('lojas_codigo_interno_key', 'lojas', type_='unique')
    op.drop_column('lojas', 'telefone')
    op.drop_column('lojas', 'nome')
    op.drop_column('lojas', 'codigo_interno')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lojas', sa.Column('codigo_interno', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lojas', sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lojas', sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('lojas_codigo_interno_key', 'lojas', ['codigo_interno'])
    op.drop_column('lojas', 'contact')
    op.drop_column('lojas', 'name')
    # ### end Alembic commands ###
