"""fixed enum roles

Revision ID: 6fe65f10050a
Revises: a79025a5f080
Create Date: 2025-04-20 13:56:47.936477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fe65f10050a'
down_revision: Union[str, None] = 'a79025a5f080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('owner', 'costumer', 'employee', name='roleenum'),
               type_=sa.Enum('admin', 'manager', 'employee', name='roleenum', native_enum=False),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'manager', 'employee', name='roleenum', native_enum=False),
               type_=postgresql.ENUM('owner', 'costumer', 'employee', name='roleenum'),
               nullable=True)
    # ### end Alembic commands ###
