"""fixed enum roles 8.0

Revision ID: c1201a92afae
Revises: dda2571977a1
Create Date: 2025-04-20 14:27:08.846975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1201a92afae'
down_revision: Union[str, None] = 'dda2571977a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        CREATE TYPE roleenum AS ENUM ('admin', 'manager', 'employee');
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
