"""added field to stock entity

Revision ID: d079452d95a0
Revises: 9e03c2b89c25
Create Date: 2025-04-19 14:47:36.518820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd079452d95a0'
down_revision: Union[str, None] = '9e03c2b89c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('used_quantity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'used_quantity')
    # ### end Alembic commands ###
