"""changed name of columns in stcok

Revision ID: d6d0d7e502ca
Revises: d079452d95a0
Create Date: 2025-04-19 14:59:01.951805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d0d7e502ca'
down_revision: Union[str, None] = 'd079452d95a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('total_quantity', sa.Float(), nullable=True))
    op.drop_column('stock', 'quantity_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('quantity_available', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('stock', 'total_quantity')
    # ### end Alembic commands ###
