"""fixed enum roles 7.0

Revision ID: dda2571977a1
Revises: f77444a9d48c
Create Date: 2025-04-20 14:21:45.070568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda2571977a1'
down_revision: Union[str, None] = 'f77444a9d48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TYPE roleenum AS ENUM ('admin', 'manager', 'employee');
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
