"""fixed enum roles 6.0

Revision ID: f77444a9d48c
Revises: 30f48c17ed01
Create Date: 2025-04-20 14:11:39.602415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77444a9d48c'
down_revision: Union[str, None] = '30f48c17ed01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role TYPE roleenum
        USING role::text::roleenum;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('owner', 'costumer', 'manager', 'employee', name='roleenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('owner', 'costumer', 'manager', 'employee', name='roleenum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###
